### ISSUE TITLE
Hygieia Github Collector is not fetching old commits

### ISSUE THREAD

**Issue by MustafUddinAhmed** [Hygieia/hygieia-scm-github-collector#17]
My github-scm-collector is not fetching commits from last 7 days, Rather it is showing only recent commits. How to solve this Problem?

**Comment by kumarabhishek0809** [comment]
Team will you please share configuration for Github proxy, I am trying for first time.

**Comment by MustafUddinAhmed** [comment]
Ya sure, You can refer to this document-

[Github Configuration](https://hygieia.github.io/Hygieia/github.html)

**Comment by karlpanganiban** [comment]
@MustafUddinAhmed experienced the same thing. 

What I have observed is the time you bring up the collector, it won't fetch the existing commits. It will just ONLY fetch the new ones coming in.

I'm not sure if that's really how it works, or maybe I have some misconfiguration. But just keep the collector up and running, you won't have any issues on the new ones.

**Comment by MustafUddinAhmed** [comment]
@karlpanganiban exactly the same issue I was facing.
I haven't found the solution yet (how it will fetch the previous commits)
For new commits, there is no issue.
