### ISSUE TITLE
How to contribute a collector

### ISSUE THREAD

**Issue by davidpolaniaac** [Hygieia/hygieia-scm-github-collector#30]
How can I contribute a new git collector for the organization this would be for Azure DevOps Git. How can I create the repository and publish it. If it is possible to guide me. Thank you

**Comment by VivekBuzruk** [comment]
From the technical front, you can check --> https://hygieia.github.io/Hygieia/create_collector.html.

**Comment by davidpolaniaac** [comment]
@VivekBuzruk thanks! I have already contributed the collector, what I have not found is how to propose it to be added to the organization in github

**Comment by rvema** [comment]
@davidpolaniaac please ping me in gitter and we can work on having it integrated on Hygieia GitHub Organization
