### ISSUE TITLE
Github Collector 401 unauthorized error on UI.

### ISSUE THREAD

**Issue by sudhanshusr** [Hygieia/hygieia-scm-github-collector#5]
Github Collector is showing 401 unauthorised issue on UI. 

#github.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false	
logging.file=./logs/github.log
github.cron=0 0/5 * * * *
github.host=github.com
github.commitThresholdDays=15
github.errorThreshold=1

#Key Generated by Hygiea-Core also added to api.properties as key
github.key=GZGhoUnq+2u2qywEpHWhkUWukWvQ1WIg 

#Generated from developer setting github
github.personalAccessToken=829bb3ddae294945a3xxxxxxxxxxxxxxxxx

java -jar github-scm-collector-3.0.2-SNAPSHOT.jar --spring.config.name=github --spring.config.location=C:\Devops\Hygieia\Hygieia\collectors\scm\github\target\github.properties

![image](https://user-images.githubusercontent.com/10558551/55715690-e5091680-5a12-11e9-8f59-9e6a3a622227.png)

![image](https://user-images.githubusercontent.com/10558551/55715620-b8ed9580-5a12-11e9-8a0a-e415bd749ce2.png)

**Comment by Sbrenthughes** [comment]
This looks to be related to https://github.com/Hygieia/Hygieia/issues/2978

**Comment by Sbrenthughes** [comment]
Closing for now. Once the above as been resolved and you are still experiencing issues please reopen another issue
